language: dart

dart:
  - stable

dart_task:
  - test: --platform chrome --no-chain-stack-traces
  - dartanalyzer: --fatal-infos --fatal-warnings lib
  - dartfmt

  # Only building master means that we don't run two builds for each pull request.
branches:
  only: [master]

cache:
 directories:
   - $HOME/.pub-cache