name: reactify
version: 1.0.0
author: Dave Fort <ptiger10@gmail.com>
documentation:
repository: https://github.com/ptiger10/reactify
homepage: 
description: 'Reactive user interface components in pure Dart'
environment:
  sdk: '>=2.0.0 <3.0.0'
dev_dependencies:
  test: ^1.0.0
