name: reactify
version: 1.0.1
author: Dave Fort <ptiger10@gmail.com>
documentation:
homepage: https://github.com/ptiger10/reactify
description: '
This library makes it easier to build reactive user interface components in pure Dart. 
It is intended to be used in framework-less web development.
'
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  meta: ^1.0.0
dev_dependencies:
  test: ^1.0.0
