name: main
dependencies:
  # reactify: ^1.0.0
  reactify:
    path: /Users/davidfort/Google-Drive/coding-projects/open-source/reactify
dev_dependencies:
  build_runner: ^1.3.0
  build_web_compilers: ^2.0.0
  build_daemon: ^1.0.0

